---
version: "0.1"

runson: ${matrix.os}

matrix:
  os:
    - win
  files:
    - exampleheading.test.js
    - examplelink.test.js
    - exampleparagraph.test.js
    - exampletitle.test.js

pre:
  - npm install
  - npx playwright install

cacheKey: '{{ checksum "package-lock.json" }}'

cacheDirectories:
  - node_modules

testSuites:
  - npx jest "$files" --runInBand

jobLabel:
  - playwright-JestJS
  - win
  - matrix